-- MySQL Script generated by MySQL Workbench
-- Mon Jun  2 15:56:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project` DEFAULT CHARACTER SET utf8mb3 ;
USE `Project` ;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `country_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `country_list` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `hash_salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `complete` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `UKk8d0f2n7n88w1a16yhua64onx` ON `users` (`user_name` ASC) VISIBLE;

CREATE UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` ON `users` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `country_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `country_plan` (
  `countryplan_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT NULL,
  `start_time` DATETIME(6) NULL DEFAULT NULL,
  `total_days` INT NULL DEFAULT NULL,
  PRIMARY KEY (`countryplan_id`),
  CONSTRAINT `fk_country_plan_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `country_list` (`country_id`),
  CONSTRAINT `fk_country_plan_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_country_plan_user` ON `country_plan` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_country_plan_country` ON `country_plan` (`country_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `journey` (
  `journey_id` INT NOT NULL AUTO_INCREMENT,
  `attraction` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `memo` VARCHAR(255) NULL DEFAULT NULL,
  `days` INT NULL DEFAULT NULL,
  `time` DATETIME(6) NULL DEFAULT NULL,
  `countryplan_id` INT NULL DEFAULT NULL,
  `isdelete` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`journey_id`),
  CONSTRAINT `fk_journey_countryplan_id`
    FOREIGN KEY (`countryplan_id`)
    REFERENCES `country_plan` (`countryplan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_journey_countryplan_id_idx` ON `journey` (`countryplan_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `travel_money`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_money` (
  `money_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `dollar` DOUBLE NULL DEFAULT NULL,
  `money_date` DATETIME(6) NULL DEFAULT NULL,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`money_id`),
  CONSTRAINT `fk_travel_money_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_travel_money_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_travel_money_user_id_idx` ON `travel_money` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_travel_money_category_idx` ON `travel_money` (`category_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
